name: pull_request

on: [pull_request]

jobs:
  test:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Test and build
        run: ./gradlew build

      - name: Run sonar build
        run: ./gradlew sonarqube
